#include "input.h"

const BYTE KEYPAD_MAP[KEYPAD_KEY_COUNT] = {
	SDL_SCANCODE_1,
	SDL_SCANCODE_2,
	SDL_SCANCODE_3,
	SDL_SCANCODE_Q,
	SDL_SCANCODE_W,
	SDL_SCANCODE_E,
	SDL_SCANCODE_A,
	SDL_SCANCODE_S,
	SDL_SCANCODE_D,
	SDL_SCANCODE_Z,
	SDL_SCANCODE_X,
	SDL_SCANCODE_C,
	SDL_SCANCODE_4,
	SDL_SCANCODE_R,
	SDL_SCANCODE_F,
	SDL_SCANCODE_V
};

WORD getKeyBitmask(SDL_Scancode scancode) {
	for (BYTE i = 0; i < KEYPAD_KEY_COUNT; i++) {
		if (KEYPAD_MAP[i] == scancode) {
			return 1 << i;
		}
	}

	return WRONG_INPUT;
}
